import * as fs from 'fs';
import * as path from 'path';

function stripComment(line: string): string {
    let commentIndex = -1;
    for (let i = 0; i < line.length; i++) {
        if (line[i] === '#') {
            commentIndex = i;
            break;
        }
        if (i + 1 < line.length && line[i] === '/' && line[i+1] === '/') {
            commentIndex = i;
            break;
        }
        if (line[i] === '(') {
            commentIndex = i;
            break;
        }
    }
    if (commentIndex >= 0) line = line.substring(0, commentIndex);
    return line.trimEnd();
}

export function extractTreeLines(content: string): string[] {
    const lines = content.split(/\r?\n/);
    const result: string[] = [];
    let inTree = false;

    for (let i = 0; i < lines.length; i++) {
        const rawLine = lines[i];
        let line = stripComment(rawLine);
        if (line.trim() === '') {
            if (inTree) break;
            continue;
        }

        const hasBoxDrawing = /[├└│─\+\-\\|]/.test(line);
        const trimmed = line.trimStart();
        const leadingSpaces = line.length - trimmed.length;
        const hasIndent = leadingSpaces > 0 || (i === 0 && result.length === 0);
        const endsWithSlash = trimmed.endsWith('/');
        const hasFileExt = /\.\w+$/.test(trimmed) && !trimmed.includes(' ');

        const looksLikeTree = hasBoxDrawing || (hasIndent && (endsWithSlash || hasFileExt));

        if (looksLikeTree) {
            inTree = true;
            result.push(line);
        } else if (inTree) {
            break;
        }
    }
    return result;
}

export function parseTreeToStructure(lines: string[], basePath: string) {
    if (!fs.existsSync(basePath)) fs.mkdirSync(basePath, { recursive: true });

    const stack: { path: string; depth: number }[] = [{ path: basePath, depth: -1 }];

    for (const rawLine of lines) {
        let line = rawLine.trimEnd();
        if (line === '') continue;

        let depth = 0;
        let isFolder = line.endsWith('/');
        let name = isFolder ? line.slice(0, -1) : line;

        const hasBoxDrawing = /[├└│─\+\-\\|]/.test(line);
        if (hasBoxDrawing) {
            name = line.replace(/^[├└│─\+\-\\| ]+/, '').trim();
            if (name === '') continue;
            isFolder = name.endsWith('/');
            if (isFolder) name = name.slice(0, -1);
            const prefix = line.substring(0, line.indexOf(name));
            depth = (prefix.match(/[├└│\+\-\\|]/g) || []).length;
        } else {
            const leadingSpaces = line.search(/\S/);
            depth = Math.floor(leadingSpaces / 2);
            const entry = line.trim();
            isFolder = entry.endsWith('/');
            name = isFolder ? entry.slice(0, -1) : entry;
        }

        while (stack.length > 1 && stack[stack.length - 1].depth >= depth) {
            stack.pop();
        }
        const parentPath = stack[stack.length - 1].path;
        const fullPath = path.join(parentPath, name);

        if (isFolder) {
            if (!fs.existsSync(fullPath)) {
                fs.mkdirSync(fullPath, { recursive: true });
                console.log(`created folder: ${fullPath}`);
            } else {
                console.log(`folder exists: ${fullPath} (merging)`);
            }
            stack.push({ path: fullPath, depth });
        } else {
            const parentDir = path.dirname(fullPath);
            if (!fs.existsSync(parentDir)) fs.mkdirSync(parentDir, { recursive: true });
            if (!fs.existsSync(fullPath)) {
                fs.writeFileSync(fullPath, `// auto-generated by create.tre\n// ${name}\n`, 'utf8');
                console.log(`created file: ${fullPath}`);
            } else {
                console.log(`file exists, skipping: ${fullPath}`);
            }
        }
    }
}